//TODO DYNAMIC MAP
//? TODO userLocation is default for center of map on Homepage load.
//? TODO create new useState to change map in Context
//? TODO filter through data in repProfileComponent to find correct boundary data and setState
//? TODO create useEffect in Map that has this state as a dependency
//? TODO make paths variable dynamic enough to load any shape data that is sent to it.
//? TODO in RepProfileComponent make onClick in Wrapper that changes the state in Context that changes the map.
//TODO REGINA MLA BOUNDARY SHAPE NOT WORKING? SHOWING UNDEFINED BUT ROUTING SEEMS FINE.

//TODO HEADER
//*? MAKE SIGN IN OR DELETE BUTTONS
//*? MAKE LOGO LINK TO HOMEPAGE IF THERE IS SOMETHING IN LOCAL STORAGE
//*? MAKE LINK TO POSTAL CODE FOR PAGE TITLED "FIND YOUR REPRESENTATIVES" WITH A MAGNIFYING GLASS ICON.

//TODO REP PROFILES
//* TODO FIX BUG IN CALGARY AND REGINA WHERE REP IMG NOT FOUND. FETCH IS FAILING. NEED TO CHANGE CONDITION TO ACCOUNT FOR FETCH FAILURE.

//?  TODO IF THERE ARE NO REPRESENTATIVES IN BRANCH OF GOVERNMENT, DISPLAY ERROR MESSAGE OR DISPLAY NOTHING.

//* TODO Limit number of local reps shown to 4 or 5. Make the rest visible by clicking on a tab that shows you the rest.

//* make map fixed to top of screen with framer motion.

//TODO MAKE SURE PROVINCIAL POLYGONS ARE WORKING:
// === polygons are working:
//? === polygons AND zoom working
//Make zoom revert to userLocation on unMount

//?"Quebec" H2V4J1,
//?"Alberta" T1Y 7J9, T1K 8A8,
//?"Ontario" M5J 0A1,
//?"Nova Scotia" B3J 1Y4,change zoom to be closer
//?"New Brunswick" E1C 0R9, change zoom to be closer
//?"Manitoba" R2M 3T9,
//?"British Columbia" V8T1Y3, FIND POLYGON FOR ISLANDS AND ADD THEM
//?"Prince Edward Island" C0A 1Y0, Zoom for Federal MP needs to be lower
//?duplicate Provincial MLA/Premier bug needs to be fixed?
//"Saskatchewan" S4P 0P9 MLA boundary doesn't exist. set default to local mayor
//? "Newfoundland and Labrador" A1C 1G9 Councillor zoom should be same as Mayor
//*TERRITORIES - currently not able to find representatives with postal code. Check to see if address works better.
// "Yukon" Y1A 2A7;
// "Nunavut" X0A 0H0;
// "Nortwest Territories" X1A 2R3;

//* TEMPLATE FOR ELECTION INFO FOR PREMIERS DATASET
// "election_info": {
//     "election_date": "November 7, 2022",
//     "election_website": "https://www.elections.gov.nl.ca/elections/"
// },

//*PRESENTATION

//* WELCOME TO OPACITY, AN WEB APP THAT HELPS MAKE GOVERNMENT LESS OPAQUE BY FINDING YOUR LOCAL ELECTED REPRESENTATIVES AT THE MUNICIPAL, PROVINCIAL, AND FEDERAL LEVEL BASED ON YOUR POSTAL CODE.

//*1 START IN QUEBEC H2V4J1
//REPRESENTATIVES PROFILES
//DYNAMIC MAP
//DIFFERENT MAP SHAPES OF EACH BRANCH
//SHOW OFF MOBILE RESPONSIVENESS
//TALK ABOUT ELECTIONS AND REGISTRATION DATA

//*2 MOVE TO NEWFOUNDLAND A2H2V3
//SHOW WHAT HAPPENS WHEN THERE IS NO MUNICIPAL DATA AVAILABLE

//*3 MOVE TO VANCOUVER V6B 2L3
//SHOW DIFFERENCE IN LOCAL DATASETS

//* 7. HOW THE SITE WORKS
//1. WHEN THE USER ENTERS A POSTAL CODE, SEVERAL THINGS HAPPEN TO GENERATE THE HOMEPAGE:
// A. THE POSTAL CODE IS SENT TO THE GOOGLE GEOCODING API TO FIND THE LAT & LNG AND PROVINCE NAME ASSOCIATED TO THE POSTAL CODE.
//B. THESE COORDINATES ARE THEN USED TO FETCH THE REPRESENTATIVES AND BOUNDARY SHAPES ASSOCIATED WITH THOSE COORDINATES FROM THE REPRESENT API, WHICH IS A DB HOSTING THIS INFORMATION. THE SITE ALSO FETCHES THE PREMIERS DATABASE I CREATED IN MONGO DB. THE COORDINATES ARE ALSO STORED IN LOCAL STORAGE SO THE BASIC INFORMATION WITH STAY ON REFRESH.
//C. THESE DATASETS ARE THEN SORTED INTO VARIOUS CATEGORIES AND FORMATTED BY A PROFILE COMPONENT AND MAP COMPONENT.

//* 1. START BY ENTERING YOUR POSTAL CODE -

//* 2. THE SITE THEN GENERATES A HOMEPAGE WITH THE REPRESENTATIVES ASSOCIATED WITH YOUR LOCATION.

//* 3. AT THE TOP OF THE PAGE THERE IS A MAP THAT CHANGES DYNAMICALLY BASED ON THE POSTAL CODE ENTERED, AND WILL DISPLAY THE ELECTORAL DISTRICTS OF ANY REPRESENTATIVE THAT HAS BEEN SELECTED.

//* 4. THE REPRESENTATIVES ARE ORGANIZED BASED ON THEIR BRANCH OF GOVERNMENT.
//* 5. REP PROFILES:
//  THE DATASETS FOR THE REPRESENTATIVES RECEIVED BY THE API CAN VARY QUITE A LOT FROM ONE REPRESENTATIVE TO ANOTHER, BUT EACH REPRESENTATIVE HAS THEIR TITLE, DISTRICT, EMAIL ADDRESS AND PARTY AFFILIATION.
//  OTHER CONTACT INFORMATION IS CONDITIONALLY RENDERED BASED ON AVAILABILITY WITHIN THE DATASET RETRIEVED BY THE API.
//  LINKS
// EMAIL LINKS WILL OPEN THE USER'S EMAIL CLIENT AND A NEW EMAIL ADDRESSED TO THE REPRESENTATIVE.
//THE WEBSITE LINKS OPEN A NEW TAB TO THE REPRESENTATIVES PERSONAL WEBSITE (WHEN ONE IS AVAILABLE) THAT PROVIDE MORE DETAILED INFORMATION ABOUT THE REPRESENTATIVE'S ROLES WITHIN GOVERNMENT.
//SOCIAL MEDIA LINKS WILL OPEN NEW TABS TO THE SOCIAL MEDIA PROFILES.
//THE OFFICE ADDRESSES WILL OPEN A NEW TAB IN THE USER'S BROWSER WITH A GOOGLE MAPS SEARCH OF THE ADDRESS THAT WAS CLICKED.
// PHONE NUMBERS WILL OPEN THE USER'S PHONE CLIENT ON MOBILE, OR ON THEIR LAPTOP/PC

//THE SITE IS ALSO MOBILE RESPONSIVE, AS I ASSUME MOPST USERS WOULD BE LOOKING FOR THIS INFORMATION ON THEIR PHONES.
//* 6. ELECTIONS
//AT THE BOTTOM OF THE PROVINCIAL AND FEDERAL REPRESENTATIVE BOXES THE DATE OF THE NEXT ELECTION IS DISPLAYED, ALONG WITH A BUTTON THAT TAKES THE USER TO THE ASSOCIATED ELECTIONS WEBSITE WHERE THEY CAN REGISTER TO VOTE AND FIND MORE INFORMATION.
//THESE DATES COME FROM A MONGO DATABASE OF ALL OF THE PREMIERS THAT I CREATED TO GENERATE THE PREMIER'S INFORMATION PROVINCIAL MAP SHAPES, AND ELECTION INFORMATION.

//* 8. CHALLENGES
//THE MUNICIPAL DATASETS ARE REALLY INCONSISTENT BECAUSE THERE ARE SO MANY MUNICIPAL WEBSITES, AND OFTEN THERE WILL BE DEAD LINKS TO REPRESENTATIVE PROFILE PICTURES OR WEBSITES.

//MONTREAL H2V4J1 - MY HOME POSTAL CODE. FAMILIAR FACES FOR STUDENTS
//VANCOUVER V6B 2L3 - GOOD EXAMPLE OF LARGER MUNICIPAL DATASET
// CORNERBROOK NEWFOUNDLAND A2H2V3 - EXAMPLE OF WHAT HAPPENS WHEN THERE ARE NO MUNICIPAL REPRESENTATIVES FOUND

//potential
//EDMONTON T5K 1H5
// SUDBURY P3C 2N3
